export const cities = [
  "Kota Pekanbaru",
  "Kota Batam",
  "Kota Adm. Jakarta Pusat",
  "Kota Adm. Jakarta Utara",
  "Kota Adm. Jakarta Barat",
  "Kota Adm. Jakarta Selatan",
  "Kota Adm. Jakarta Timur",
  "Kab. Bogor",
  "Kab. Bandung",
  "Kab. Bekasi",
  "Kab. Bandung Barat",
  "Kota Bogor",
  "Kota Bandung",
  "Kota Cirebon",
  "Kota Bekasi",
  "Kota Depok",
  "Kota Cimahi",
  "Kab. Semarang",
  "Kota Semarang",
  "Kab. Sleman",
  "Kota Yogyakarta",
  "Kota Malang",
  "Kota Surabaya",
  "Kab. Tangerang",
  "Kota Tangerang",
  "Kota Tangerang Selatan",
];
