export const majors = [
  "Accounting",
  "Architecture",
  "Biology",
  "Business Administration",
  "Business Information Systems",
  "Business Management",
  "Business Management and Marketing",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Clinical and Community Pharmacy",
  "Communication Science",
  "Communications",
  "Computer Science",
  "Dental Medicine",
  "Dentistry",
  "Dentistry Medicine",
  "Economics",
  "Electrical Engineering",
  "Engineering Physics",
  "Entrepreneurship",
  "Environmental Engineering",
  "Fashion Design",
  "Fashion Management",
  "Geodesy and Geomatics Engineering",
  "Geological Engineering",
  "Geomatics Engineering",
  "Geophysics Engineering",
  "Graphic Design",
  "Industrial and Systems Engineering",
  "Informatics",
  "Information System",
  "International Accounting and Finance",
  "International Business",
  "International Relations",
  "Islamic Economics",
  "Law",
  "Management",
  "Materials and Metallurgical Engineering",
  "Mechanical Engineering",
  "Medicine",
  "Metallurgy and Material Engineering",
  "Meteorology",
  "Naval Architecture and Shipbuilding Engineering",
  "Nursing",
  "Pharmaceutical Science and Technology",
  "Pharmacy",
  "Psychology",
  "Public Health",
  "Statistics",
  "Urban and Regional Planning",
  "Veterinary Medicine",
];
